# Generated by Django 2.2 on 2021-10-16 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='BallincolligPropertyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=254)),
                ('full_address', models.TextField()),
                ('price', models.IntegerField(default=200000)),
                ('sold_date', models.CharField(max_length=254)),
                ('longitude', models.CharField(max_length=254)),
                ('latitude', models.CharField(max_length=254)),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PropertyTypeModel')),
            ],
        ),
    ]
